language: node_js
node_js:
- '0.12'
script: npm run build
env:
  global:
    secure: NcH7ELjgfEdQsZrtW/J1ivDsxQozC/VDQE/j1dVkAvLMOUKx3BU+0fgIaTjd7gDqmYkTLEF2Y5HkKg4HpGLbqLViYgr46sh1uJioHcdJCZQYEPJMlQ4asHG2kRym2hvDl9N4maRyJptm/FM73noF37jIY5NTVSxUKJyW9xZyL4vbhfdFPQWxyfQIZsru+WRh9tbP2Pp3NfeLXhweuaNRWkjxUY1wRq0WbSUBHlG5uPepYr+8ZXkVpm+SeoTlI+beZoYZ0uN4EhW8uCS/V1MzxzYbqRheGGEtrStCtyRtLXw28FAfms3aJEilVvbtCkl54bk9OIrmqKxbLpxX+SfepRY4R9uLBW27H28ZXxuMAg5/cdY8hVyyanQwkcoSX12c4yWLaHTpE6BKFB+kY8m06A88hFZdMsQ7mPZOfpXUtLGFJbPbsKc3vJqC5ra0PvVgn4NIrF+KtJNpBSdjNaeEgtIDccwCwaFxhP6rBSKrdXSOfzsMsV2uKupW05HsIK6lASBUj7asxL6bIgfI5pxo4FYUmZMBnv9zrXf+O1aXCI5wJO2m88aBRpfQbqJYIzJRbDyZEqbYRCIRO9mvg1KqR5s+AaSvZIYIvMMGWgJtP+f4aHtz/4Tszv4XcAAZ+DGI2i8+WVTrEMj3gGHzGU2CIiWOljOr/Ipcuil+IUzHLZI=
